//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PD_CusTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_PD_Process
    {
        public int ID { get; set; }
        public string Delivery_WO { get; set; }
        public string Delivery_TAG { get; set; }
        public string Delivery_User { get; set; }
        public string Delivery_Truck { get; set; }
        public string Delivery_Status { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public Nullable<System.DateTime> Delivery_Date_Cus { get; set; }
    }
}
