//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PD_CusTracking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Delivery_PD_Process> Delivery_PD_Process { get; set; }
        public virtual DbSet<WMS_PD_Log_Product> WMS_PD_Log_Product { get; set; }
        public virtual DbSet<WMS_PD_Master_Customer> WMS_PD_Master_Customer { get; set; }
        public virtual DbSet<WMS_PD_Master_Location> WMS_PD_Master_Location { get; set; }
        public virtual DbSet<WMS_PD_Master_SO> WMS_PD_Master_SO { get; set; }
        public virtual DbSet<WMS_PD_Master_SO_tmp> WMS_PD_Master_SO_tmp { get; set; }
        public virtual DbSet<WMS_PD_Master_Unit> WMS_PD_Master_Unit { get; set; }
        public virtual DbSet<WMS_PD_Master_User> WMS_PD_Master_User { get; set; }
        public virtual DbSet<WMS_PD_Move> WMS_PD_Move { get; set; }
        public virtual DbSet<WMS_PD_Product> WMS_PD_Product { get; set; }
        public virtual DbSet<WMS_PD_Site> WMS_PD_Site { get; set; }
        public virtual DbSet<WMS_PD_Master_Mat> WMS_PD_Master_Mat { get; set; }
        public virtual DbSet<WMS_PD_Master_Pac> WMS_PD_Master_Pac { get; set; }
        public virtual DbSet<WMS_PD_Master_Pac_tmp> WMS_PD_Master_Pac_tmp { get; set; }
    }
}
