//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PD_CusTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Record
    {
        public int R_ID { get; set; }
        public string WO_No { get; set; }
        public string Mem_Name { get; set; }
        public string Doc_Status { get; set; }
        public string Create_by { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Customer { get; set; }
        public string Driv_Name { get; set; }
        public Nullable<int> Truck_ID { get; set; }
        public string Truck_Des { get; set; }
        public string SO_No { get; set; }
        public string AWB_No { get; set; }
        public string Cust_Ref_No { get; set; }
        public Nullable<double> Advance { get; set; }
        public string Deposit { get; set; }
        public Nullable<double> Estimate { get; set; }
        public string A_Status { get; set; }
        public string DP_Status { get; set; }
        public string DC_Status { get; set; }
        public string Cust_Code { get; set; }
        public Nullable<double> Clear_Advance { get; set; }
        public Nullable<double> Special { get; set; }
        public Nullable<double> Clear_Special { get; set; }
        public string Clear_Deposit { get; set; }
        public string Date_Ex_Re { get; set; }
        public string Email_Cus { get; set; }
        public string Pass_Advance { get; set; }
        public string Customs_Entry_No { get; set; }
        public string Truck_Code { get; set; }
        public string Freight_Type { get; set; }
        public string Planned_Clear_date { get; set; }
        public string Clearance_Status { get; set; }
        public string User_App { get; set; }
        public string Data1 { get; set; }
        public string Data2 { get; set; }
        public string Data3 { get; set; }
        public string SGate_pass { get; set; }
        public string UGate_pass { get; set; }
        public string Do_No { get; set; }
        public string Objective { get; set; }
        public string Type_Service { get; set; }
        public string Tel_D1 { get; set; }
        public string Tel_D2 { get; set; }
        public string Data4 { get; set; }
        public string Data5 { get; set; }
        public string Data6 { get; set; }
        public string Data7 { get; set; }
        public string Data8 { get; set; }
        public string Truck_Start { get; set; }
        public Nullable<System.DateTime> DatePlan_Start { get; set; }
        public Nullable<System.TimeSpan> TimePlan_Start { get; set; }
        public Nullable<System.DateTime> DatePlan_End { get; set; }
        public Nullable<System.TimeSpan> TimePlan_End { get; set; }
        public Nullable<System.DateTime> DateActual_Start { get; set; }
        public Nullable<System.TimeSpan> TimeActual_Start { get; set; }
        public Nullable<System.DateTime> DateActual_End { get; set; }
        public Nullable<System.TimeSpan> TimeActual_End { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<int> Mileage_End { get; set; }
    }
}
