//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PD_CusTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Update_LOT_A
    {
        public int Id { get; set; }
        public string LOT { get; set; }
        public string LO { get; set; }
        public string STATUS { get; set; }
    }
}
