//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PD_CusTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_PD_Master_Unit
    {
        public int ID { get; set; }
        public string Unit_Code { get; set; }
        public string Unit_Des { get; set; }
        public string Unit_Status { get; set; }
    }
}
