//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PD_CusTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_PD_Move
    {
        public int ID { get; set; }
        public string PRO_ID { get; set; }
        public string PRO_Des { get; set; }
        public string PRO_Lot { get; set; }
        public Nullable<int> PRO_Quantity { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string PRO_Recive { get; set; }
        public string Data1 { get; set; }
        public string Data2 { get; set; }
        public string Data3 { get; set; }
        public string Data4 { get; set; }
        public string Data5 { get; set; }
        public string PRO_Status { get; set; }
    }
}
