//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PD_CusTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_PD_Product
    {
        public int ID { get; set; }
        public string PRO_ID { get; set; }
        public string PRO_Des { get; set; }
        public string PRO_Lot { get; set; }
        public Nullable<double> PRO_Quantity { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string PRO_Recive { get; set; }
        public string PRO_SO { get; set; }
        public string PRO_Cus { get; set; }
        public string PRO_Ref { get; set; }
        public string PRO_Shop_Packing__No { get; set; }
        public string PRO_Tag_No { get; set; }
        public string PRO_Item_No { get; set; }
        public string PRO_Package { get; set; }
        public Nullable<double> PRO_Net { get; set; }
        public Nullable<double> PRO_Gross { get; set; }
        public Nullable<double> PRO_Tare { get; set; }
        public Nullable<double> PRO_Extra { get; set; }
        public Nullable<double> PRO_Actual { get; set; }
        public string PRO_Customter_Drum_No { get; set; }
        public string PRO_Drum_Dimension { get; set; }
        public string PRO_Item_Type { get; set; }
        public string PRO_Unit { get; set; }
        public string PRO_Status { get; set; }
        public string Barcode { get; set; }
        public string Location { get; set; }
        public string Pro_Reel_No { get; set; }
        public string Pro_Check_Status { get; set; }
        public string Pro_User_Check { get; set; }
        public string Pro_Owner { get; set; }
        public string Print_TF { get; set; }
        public Nullable<double> Qty_Ship { get; set; }
        public string Ref_Barcode { get; set; }
        public string Tranfer_Sap { get; set; }
        public string Tranfer_Sap_Date { get; set; }
    }
}
